spring:
  application:
    name: picard.wms
  datasource:
    url: jdbc:postgresql://localhost:5432/wmsdb
    username: wmsuser
    password: wmspassword
  jpa:
    hibernate:
      ddl-auto: none # disable auto-creation; rely on Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: DEBUG